---
version: '3.6'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: bash -c "go build -o bin/bot && bin/bot -t ${BOT_TOKEN}"
    volumes:
      - .:/go/src/discord-bot
    tty: true
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    ports:
      - 6380:6379
