---
version: '3.7'
services:
  bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: bash -c "go build -o bin/bot && bin/bot"
    volumes:
      - .:/go/src/discord-bot
    tty: true
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    ports:
      - 6380:6379
